config/routes.rb
Rails.application.routes.draw do
  ###########################
  ### 管理者のルーティング ###
  ###########################

  # 認証機能
  # 新規登録とパスワードに関連する機能は作らない
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"  # ログイン用のルーティング
  }

  # namespaceはファイルの構成もURLも指定のパスにする
  namespace :admin do
    root to: 'homes#top'

    # genresコントローラ
    resources :genres, only: [:index, :create, :edit, :update]

    # itemsコントローラ
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # customersコントローラ
    resources :customers, only: [:index, :show, :edit, :update]

    # ordersコントローラ
    resources :orders, only: [:show, :update]

    # order_detailsコントローラ
    resources :order_details, only: [:update]
  end

  ###########################
  ###  顧客のルーティング  ###
  ###########################

  # 認証機能
  devise_for :customers, controllers: {
    registrations: "public/registrations", # 新規登録
    sessions: "public/sessions" # ログイン
  }

  # moduleはURLは変えずにファイルの構成だけ指定のパスにする
  scope module: :public do
    # homesコントローラ
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'

    # customersコントローラ
    get   'customers/my_page'          => 'customers#show',         as: 'customer'
    get   'customers/information/edit' => 'customers#edit',         as: 'edit_customer'
    get   'customers/unsubscribe'      => 'customers#unsubscribe',  as: 'unsubscribe_customer'  # 退会確認ページ
    patch 'customers/information'      => 'customers#update',       as: 'update_customer'
    patch 'customers/withdraw'         => 'customers#withdraw',     as: 'withdraw_customer'     # 退会処理

    # itemsコントローラ
    resources :items, only: [:index, :show]

    # addressesコントローラ
    resources :addresses, except: [:show, :new]

    # cart_itemsコントローラ
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :edit, :show]

    # ordersコントローラ
    get 'orders/thanks'
    resources :orders, only: [:new, :index, :show, :create]
    post 'orders/confirm'
  end
end

app/views/layouts/shared/_errors.html.erb
<% if model.errors.any? %>
  <ul class="border border-danger pr-5">
    <% model.errors.full_messages.each do |error| %>
      <li class="mb-0 text-danger"><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/shared/_flash.html.erb
<%# noticeここから %>
<% if flash[:notice] %>
  <div class="row mb-5">
    <div class="col">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<%# alertここから %>
<% if flash[:alert] %>
  <div class="row mb-5">
    <div class="col">
      <%= flash[:alert] %>
    </div>
  </div>
<% end %>

app/views/layouts/shared/_header.html.erb
<header class="mb-4">
  <nav class="navbar navbar-light navbar-expand-md py-4">
    <%= link_to "ながのCAKE", root_path, class: "navbar-brand border px-4 py-2 text-dark mb-4 mb-md-0" %>

    <div class="collapasee navbar-collapse mx-0 d-flex flex-column  ">
      <%# 未実装のリンクは # とする %>
      <ul class="navbar-nav ml-auto flex-sm-row mb-3">
        <%# adminのリンクここから %>
        <% if admin_signed_in? %>

          <li class="nav-item mr-4">
            <%= link_to "商品一覧", admin_items_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "会員一覧", admin_customers_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "注文履歴一覧", admin_root_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "ログアウト", destroy_admin_session_path, class: "border rounded p-2 nav-link text-dark", method: :delete %>
          </li>
        
        <%# customerのリンクここから %>
        <% elsif customer_signed_in? %>

          <li class="nav-item mr-4">
            <%= link_to "マイページ", customer_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "商品一覧", items_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "カート", cart_items_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "ログアウト", destroy_customer_session_path, class: "border rounded p-2 nav-link text-dark", method: :delete %>
          </li>

        <%# 未ログインユーザここから %>
        <% else %>

          <li class="nav-item mr-4">
            <%= link_to "About", about_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "商品一覧", items_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "新規登録", new_customer_registration_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "ログイン", new_customer_session_path, class: "border rounded p-2 nav-link text-dark" %>
          </li>

        <% end %>
      </ul>
      <%# 検索フォームここから %>
      <div class="ml-auto mr-4">
        <% if admin_signed_in? %>

          <%= render 'layouts/shared/search-form', form_url: admin_items_path %>

        <% else %>
          
          <%= render 'layouts/shared/search-form', form_url: items_path %>

        <% end %>
      </div>
    </div>
  </nav>

  <hr class="my-0">
</header>

app/views/layouts/shared/_search-form.html.erb
<%= form_with url: form_url, method: :get do |f| %>
  <div class="input-group">
    <%= f.text_field :item_kwg, placeholder: "Search", class: "form-control border-secondary border-right-0" %>
    <span class="input-group-append">
      <%= button_tag type: 'submit', class: "btn btn-outline-secondary border-left-0" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
        </svg><i class="bi bi-search"></i>
      <% end %>
    </span>
  </div>
<% end %>