config/routes.rb
Rails.application.routes.draw do
  ###########################
  ### 管理者のルーティング ###
  ###########################

  # 認証機能
  # 新規登録とパスワードに関連する機能は作らない
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"  # ログイン用のルーティング
  }

  # namespaceはファイルの構成もURLも指定のパスにする
  namespace :admin do
    root to: 'homes#top'

    # genresコントローラ
    resources :genres, only: [:index, :create, :edit, :update]

    # itemsコントローラ
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # customersコントローラ
    resources :customers, only: [:index, :show, :edit, :update]

    # ordersコントローラ
    resources :orders, only: [:show, :update]

    # order_detailsコントローラ
    resources :order_details, only: [:update]
  end

  ###########################
  ###  顧客のルーティング  ###
  ###########################

  # 認証機能
  devise_for :customers, controllers: {
    registrations: "public/registrations", # 新規登録
    sessions: "public/sessions" # ログイン
  }

  # moduleはURLは変えずにファイルの構成だけ指定のパスにする
  scope module: :public do
    # homesコントローラ
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'

    # customersコントローラ
    get   'customers/my_page'          => 'customers#show',         as: 'customer'
    get   'customers/information/edit' => 'customers#edit',         as: 'edit_customer'
    get   'customers/unsubscribe'      => 'customers#unsubscribe',  as: 'unsubscribe_customer'  # 退会確認ページ
    patch 'customers/information'      => 'customers#update',       as: 'update_customer'
    patch 'customers/withdraw'         => 'customers#withdraw',     as: 'withdraw_customer'     # 退会処理

    # itemsコントローラ
    resources :items, only: [:index, :show]

    # addressesコントローラ
    resources :addresses, except: [:show, :new]

    # cart_itemsコントローラ
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :edit, :show]

    # ordersコントローラ
    get 'orders/thanks'
    resources :orders, only: [:new, :index, :show, :create]
    post 'orders/confirm'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # 定数
  SHIPPING_COST = 800
  
  # enumのpayment_methodのための定数
  CREDIT_CARD_NUM = 0
  TRANSFER_NUM = 1

  # enumのstatusのための定数
  WAITING_FOR_PAYMENT_NUM = 0
  CONFIRM_NUM = 1
  CREATING_NUM = 2
  PREPARING_TO_SHIP_NUM = 3
  SHIPPED_NUM = 4
  
  # アソシエーション
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  
  # enumの設定
  enum payment_method: {
    credit_card: CREDIT_CARD_NUM, # クレジットカート
    transfer: TRANSFER_NUM        # 銀行振込
  }
  
  enum status: {
    waiting_for_payment: WAITING_FOR_PAYMENT_NUM, # 入金待ち
    confirm: CONFIRM_NUM,                         # 入金確認
    creating: CREATING_NUM,                       # 製作中
    preparing_to_ship: PREPARING_TO_SHIP_NUM,     # 発送準備中
    shipped: SHIPPED_NUM                          # 発送済
  }

  # バリデーションの設定
  validates :postal_code,    presence: true, length: {minimum: 4, maximum: 9}
  validates :address,        presence: true, length: {maximum: 50}
  validates :name,           presence: true, length: {maximum: 20}
  validates :shipping_cost,  presence: true
  validates :total_payment,  presence: true
  validates :payment_method, presence: true
  validates :status,         presence: true
  
  
  #########################
  ### enum関連のメソッド ###
  #########################
  def self.credit_card_key
    self.payment_methods.key(CREDIT_CARD_NUM)
  end
  
  def self.transfer_key
    self.payment_methods.key(TRANSFER_NUM)
  end
  
  def self.credit_card
    self.payment_methods_i18n[:credit_card]
  end
  
  def self.transfer
    self.payment_methods_i18n[:transfer]
  end

  
  #########################
  ### 定数取得のメソッド ###
  #########################
  def self.shipping_cost
    return SHIPPING_COST
  end


  ####################################
  ### order_detailsに関するメソッド ###
  ####################################
  
  # カート内商品すべてをorder_detailsとして保存
  def create_order_details(cart_items)
    OrderDetail.transaction do
      cart_items.each do |cart_item|
        order_details = OrderDetail.new
        order_details.order = self
        order_details.item = cart_item.item
        order_details.price = cart_item.item.price
        order_details.amount = cart_item.amount
        order_details.save!
      end
    end

    cart_items.destroy_all
  end


  ############################
  ### 配送先に関するメソッド ###
  ############################

  # 渡されたorderモデルの住所を登録し、登録したAddressを返す
  # 新しいおお届け先の場合はAddressを登録
  def set_address(params)
    # ログインしているユーザの住所
    if params[:select_address] == "self"
      self.postal_code = customer.postal_code
      self.address = customer.address
      self.name = customer.get_fullname 
    # 顧客によって登録された住所
    elsif params[:select_address] == "registered"
      address = customer.addresses.find(params[:address_id])
      self.postal_code = address.postal_code
      self.address = address.address
      self.name = address.name
    else
      # 新しい登録先の場合はorderに対して何もしない。
      # Order.new(order_params)の際にorder_paramsにデータが既に入っているため。
    end

    # 何も返さない
    return nil
  end

  # '〒{郵便番号} {住所} {宛先}'のフォーマットで表示
  def display_address
    '〒' + ' ' + postal_code + ' ' + address + ' ' + name
  end


  ##############################
  ### 作成日時に関するメソッド ###
  ##############################
  def formatted_created_at(time=false)

    if time
      return created_at.strftime('%Y/%m/%d %H:%M:%S')
    end
    return created_at.strftime('%Y/%m/%d')
  end


  ###########################
  ### 金額に関するメソッド ###
  ###########################

  # 配送料をのぞいた金額を返す
  def only_payment
    return total_payment - shipping_cost
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin! # 管理者としてのログインをしていないと使用できない

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.includes(:item)
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.status == 'confirm'
        update_making_status(@order)
      end
      redirect_to admin_order_path(@order.id)
    else
      @order_details = @order.order_details.includes(:item)
      flash[:alert] = "注文ステータスの更新に失敗しました。"
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def update_making_status(order_model)
    order_details = order_model.order_details
    for order_detail in order_details
      order_detail.update(making_status: 'waiting_for_production')
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<h2 class="d-inline-block bg-light mx-5 px-4 mb-5">注文履歴詳細</h2>

<div class="row">
  <div class="col">
    <dl>
      <div class="row">
        <dt class="col-3">購入者</dt>
        <dd class="col"><%= link_to @order.customer.get_fullname, admin_customer_path(@order.customer.id), class: "text-dark" %></dd>
      </div>

      <div class="row">
        <dt class="col-3">注文日</dt>
        <dd class="col"><%= @order.formatted_created_at %></dd>
      </div>

      <div class="row">
        <dt class="col-3">配送先</dt>
        <dd class="col"><%= @order.display_address %></dd>
      </div>

      <div class="row">
        <dt class="col-3">支払方法</dt>
        <dd class="col"><%= @order.payment_method_i18n %></dd>
      </div>

      <div class="row">
        <dt class="col-3">注文ステータス</dt>
        <dd class="col">
          <%= form_with model: @order, url: admin_order_path(@order.id), class: "d-flex" do |f| %>
            <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]}, {prompt: ""}, {class: "form-control w-auto mr-4"} %>
            <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </dd>
      </div>
    </dl>
  </div>
</div>

<div class="row">
  <div class="col-8">
    <table class="table">
      <thead class="thead-light">
        <tr>

        </tr>
        <th scope="col">商品名</th>
        <th scope="col">単価（税込）</th>
        <th scope="col">数量</th>
        <th scope="col">小数</th>
        <th scope="col">製作ステータス</th>
      </thead>

      <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td class="align-middle"><%= order_detail.item.name %></td>
            <td class="align-middle"><%= order_detail.item.get_price_with_tax %></td>
            <td class="align-middle"><%= order_detail.amount %></td>
            <td class="align-middle"><%= order_detail.get_total_price_with_tax %></td>
            <td class="align-middle">
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), class: "d-flex" do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]}, {prompt: ""}, {class: "form-control mr-2"} %>
                <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-4 mb-0 mt-auto">
    <dl>
      <div class="row">
        <dt class="col-6">商品合計</dt>
        <dd class="col-6"><%= number_to_currency(@order.only_payment, unit: "円", strip_significant_zeros: true) %></dd>
      </div>

      <div class="row">
        <dt class="col-6">送料</dt>
        <dd class="col-6"><%= number_to_currency(@order.shipping_cost, unit: "円", strip_significant_zeros: true) %></dd>
      </div>

      <div class="row">
        <dt class="col-6">請求金額合計</dt>
        <dd class="col-6"><b><%= number_to_currency(@order.total_payment, unit: "円", strip_significant_zeros: true) %></b></dd>
      </div>
    </dl>
  </div>
</div>